Allow cache to be accessed from multiple threads
Huh, didn't expect it to reject multithreading by default. Using the cache
fails with...

  ProgrammingError: SQLite objects created in a thread can only be used in that
  same thread.The object was created in thread id 140437876885248 and this is
  thread id 140437570447104

SQLite has a parameter to drop this check. Should be safe since we do the
locking ourselves. There's discussion about the option on...

  https://bugs.python.org/issue27113