Fix unit tests
I don't run Nyx's unit tests very often so a few regressions slipped in. Some
due to Nyx adjustments, some from Stem.

Stem renamed its is_pep8_available() function to
is_pycodestyle_available() because the upstream project renamed itself...

  Traceback (most recent call last):
    File "./run_tests.py", line 80, in <module>
      main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 289, in wrapped
      return func(*args, **kwargs)
    File "./run_tests.py", line 46, in main
      if stem.util.test_tools.is_pep8_available():
  AttributeError: module 'stem.util.test_tools' has no attribute 'is_pep8_available'