Port of zero causes stacktrace
Somehow an entry of '0.0.0.0:0' is among my outbound connections. Proper fix
will be to figure out where that's coming from, but for now just making a quick
hack so we don't error...

  File "/home/atagar/Desktop/nyx/nyx/connections/conn_entry.py", line 469, in get_type
    if is_exiting_allowed(controller, self.foreign.get_address(), self.foreign.get_port()):
  File "/home/atagar/Desktop/nyx/nyx/connections/conn_entry.py", line 1035, in is_exiting_allowed
    result = our_policy and our_policy.can_exit_to(ip_address, port)
  File "/home/atagar/Desktop/nyx/stem/util/lru_cache.py", line 135, in wrapper
    result = user_function(*args, **kwds)
  File "/home/atagar/Desktop/nyx/stem/exit_policy.py", line 286, in can_exit_to
    if rule.is_match(address, port, strict):
  File "/home/atagar/Desktop/nyx/stem/exit_policy.py", line 749, in is_match
    raise ValueError("'%s' isn't a valid port" % port)
  ValueError: '0' isn't a valid port