Header panel testing failure due to system calls
System calls by our tests caused our nyx cpu time assertion to fail...

  ======================================================================
  FAIL: test_sample (panel.header.TestHeader)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/nyx/test/panel/header.py", line 151, in test_sample
      self.assertEqual(0.11, vals.nyx_total_cpu_time)
  AssertionError: 0.11 != 1.6735180473327638

  ----------------------------------------------------------------------