Python3 stacktrace when dates are on a year boundary
Oops, python3 compatibility issue...

  https://trac.torproject.org/projects/tor/ticket/24820

  >>> import time
  >>> time.mktime(list(time.strptime('2017', '%Y')))
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  TypeError: Tuple or struct_time argument required

As above, this needs to be swapped to a tuple. I'm a tad tempted to simply
subtract 31536000 (the number of seconds in a year) from the unix timestamp
instead, but on reflection there's leap years, leap seconds, and god knows
what else so... meh.