Use items() rather than iteritems()
Python 3.x dropped the iteritems() method since items() now provides an
iterator...

  AttributeError: 'dict' object has no attribute 'iteritems'