Smaller screen resolutions broke rendering config panel
Oops! We need to be careful never to allow crop sizes to be negative. Seems the
following code has size checks so hopefully this is the only spot...

  Traceback (most recent call last):
    File "/usr/local/bin/nyx", line 14, in <module>
      nyx.main()
    ...
    File "/usr/local/lib/python2.7/dist-packages/nyx/panel/config.py", line 328, in _draw_selection_details
      subwindow.addstr(2, 2, 'Value: %s (%s)' % (selected.value(), str_tools.crop(attr, subwindow.width - len(selected.value()) - 13)), selected_color, BOLD)
    File "/usr/local/lib/python2.7/dist-packages/stem/util/str_tools.py", line 203, in crop
      raise ValueError("Crop size can't be negative (received %i)" % size)
  ValueError: Crop size can't be negative (received -12)