Resizing could cause nyx to crah
Another great catch from Dbryrtfbcbhgf...

  https://trac.torproject.org/projects/tor/ticket/24382

  Traceback (most recent call last):
    File "/usr/local/bin/nyx", line 11, in <module>
      sys.exit(main())
    ...
    File "/usr/local/lib/python3.5/dist-packages/nyx/__init__.py", line 716, in redraw
      panel.redraw(force = force, top = occupied)
    File "/usr/local/lib/python3.5/dist-packages/nyx/panel/__init__.py", line 175, in redraw
      self._last_draw_size = nyx.curses.draw(self._draw, top = self._top, height = self.get_height(), draw_if_resized = draw_dimension)
    File "/usr/local/lib/python3.5/dist-packages/nyx/curses.py", line 740, in draw
      curses_subwindow = CURSES_SCREEN.subwin(subwindow_height, subwindow_width, top, left)
  _curses.error: curses function returned NULL