Standardize on allowing multiple styling attributes
We changed addstr() to allow multiple styling attributes. Changing our other
draw methods as well since we now expect it from them...

  Traceback (most recent call last):
    File "./run_nyx", line 60, in <module>
      main()
    File "./run_nyx", line 17, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 288, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 91, in main
      curses.wrapper(nyx.controller.start_nyx)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
      return func(stdscr, *args, **kwds)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 570, in start_nyx
      control.redraw(False)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 401, in redraw
      panel_impl.redraw(force)
    File "/home/atagar/Desktop/nyx/nyx/log_panel.py", line 828, in redraw
      panel.Panel.redraw(self, force_redraw, block)
    File "/home/atagar/Desktop/nyx/nyx/util/panel.py", line 433, in redraw
      self.draw(self.max_x, self.max_y)
    File "/home/atagar/Desktop/nyx/nyx/log_panel.py", line 727, in draw
      self.addch(line_count, divider_indent, curses.ACS_ULCORNER, *divider_attr)
  TypeError: addch() takes at most 5 arguments (6 given)