Accounting for moved to_camel_case() util
Prior to stem's release I decided that the to_camel_case() function in the
str_tools util wasn't something that I want to vend to stem users. This in turn
broke our menu...

Traceback (most recent call last):
  File "./src/starter.py", line 478, in <module>
    cli.controller.startTorMonitor(time.time() - initTime)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 564, in startTorMonitor
    curses.wrapper(drawTorMonitor, startTime)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 635, in drawTorMonitor
    cli.menu.menu.showMenu()
  File "/home/atagar/Desktop/arm/src/cli/menu/menu.py", line 80, in showMenu
    menu = cli.menu.actions.makeMenu()
  File "/home/atagar/Desktop/arm/src/cli/menu/actions.py", line 27, in makeMenu
    baseMenu.add(makeViewMenu())
  File "/home/atagar/Desktop/arm/src/cli/menu/actions.py", line 93, in makeViewMenu
    label = " / ".join([str_tools.to_camel_case(panel.getName()) for panel in pagePanels])
AttributeError: 'module' object has no attribute 'to_camel_case'

Swapping arm to use stem's private method. This is, of course, bad since stem
may change it in the future but this'll do the trick at least until we come up
with a more permanent solution while rewriting arm.