Update *.order nyxrc options
Good point from Derrick Oswald that trying to run nyx with our sample nyxrc
errors...

  ValueError: The 'MAN PAGE ENTRY' entry of config entry
  'features.config.order' wasn't in the enumeration (expected NAME, VALUE,
  VALUE_TYPE, CATEGORY, USAGE, SUMMARY, DESCRIPTION, MAN_PAGE_ENTRY, IS_SET)

Options were no longer in sync with what nyx supported. Some were renamed, and
a few removed.