Don't crash when 'man tor' is unavailable
Oops, forgot to suppress exceptions here...

Traceback (most recent call last):
  File "runner.py", line 3, in <module>
    arm.starter.main()
  File "/home/atagar/Desktop/arm/arm/starter.py", line 505, in main
    _loadConfigurationDescriptions(pathPrefix)
  File "/home/atagar/Desktop/arm/arm/starter.py", line 211, in _loadConfigurationDescriptions
    arm.util.torConfig.loadOptionDescriptions()
  File "/home/atagar/Desktop/arm/arm/util/torConfig.py", line 179, in loadOptionDescriptions
    manCallResults = system.call("man tor")
  File "/usr/lib/python2.7/stem/util/system.py", line 860, in call
    raise exc
OSError: man tor returned exit status 16