Exception when running 'run_arm --help'
Stacktrace due to having two 'config' attributes.

Traceback (most recent call last):
  File "./run_arm", line 47, in <module>
    main()
  File "./run_arm", line 16, in main
    arm.starter.main()
  File "/home/atagar/Desktop/arm/stem/util/conf.py", line 288, in wrapped
    return func(*args, config = config, **kwargs)
  File "/home/atagar/Desktop/arm/arm/starter.py", line 43, in main
    print arm.arguments.get_help()
  File "/home/atagar/Desktop/arm/arm/arguments.py", line 142, in get_help
    event_flags = msg('misc.event_types'),
  File "/home/atagar/Desktop/arm/stem/util/conf.py", line 288, in wrapped
    return func(*args, config = config, **kwargs)
TypeError: msg() got multiple values for keyword argument 'config'