Max recursion depth error when resizing terminal
When squishing the terminal I can occasionally trigger a maximum recursion
loop...

	Traceback (most recent call last):
		...
  	File "/home/atagar/Desktop/nyx/nyx/panel/log.py", line 326, in _draw
    	self.redraw()
  	File "/home/atagar/Desktop/nyx/nyx/panel/__init__.py", line 175, in redraw
    	self._last_draw_size = nyx.curses.draw(self._draw, top = self._top, height = self.get_height(), draw_if_resized = draw_dimension)
  	File "/home/atagar/Desktop/nyx/nyx/curses.py", line 746, in draw
    	func(_Subwindow(subwindow_width, subwindow_height, curses_subwindow))
  	File "/home/atagar/Desktop/nyx/nyx/panel/log.py", line 326, in _draw
    	self.redraw()
	RuntimeError: maximum recursion depth exceeded in cmp

Adjustments made by the log panel within its draw function *should* prevent a
need to iterate a second time, but evidently that's not always the case. Simply
adjusting how we iterate to prevent a forced redraw from triggering another
forced redraw.