Simplify stem install instructions
Condensing and providing the same installation advice as Stem's site.

Also, we cannot use shutil.which() because it was added in python 3.3...

  Traceback (most recent call last):
    File "./run_nyx", line 7, in <module>
      import nyx
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 80, in <module>
      if shutil.which(cmd):
  AttributeError: 'module' object has no attribute 'which'