torrc panel stacktraced due to filter()
Anther spot where we need to standardize our use of filter(). This one
manifested as a stacktrace when viewing the torrc panel with...

  AttributeError: 'filter' object has no attribute 'strip'