AttributeError when using --debug argument
Python 3.8 removed platform.dist(), causing us to error with...

  Traceback (most recent call last):
    File "./run_nyx", line 14, in <module>
      nyx.main()
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 199, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 287, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 68, in main
      _setup_debug_logging(args)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 174, in _setup_debug_logging
      platform = ' '.join(platform.dist()),
  AttributeError: module 'platform' has no attribute 'dist'

Python doesn't have a builtin replacement, instead advising that users install
the distro package...

  https://pypi.org/project/distro/

This information isn't worth a new dependency so simply dropping it from our
debug output.