Accounting for stem's discontinued use of meets_requirements()
Stem removed the meets_requirements() method prior to its initial release...

Traceback (most recent call last):
  File "./src/starter.py", line 478, in <module>
    cli.controller.startTorMonitor(time.time() - initTime)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 564, in startTorMonitor
    curses.wrapper(drawTorMonitor, startTime)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 618, in drawTorMonitor
    control.redraw(False)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 346, in redraw
    panelImpl.redraw(force)
  File "/home/atagar/Desktop/arm/src/util/panel.py", line 405, in redraw
    self.draw(self.maxX, self.maxY)
  File "/home/atagar/Desktop/arm/src/cli/torrcPanel.py", line 178, in draw
    corrections = dict((lineNum, (issue, msg)) for lineNum, issue, msg in loadedTorrc.getCorrections())
  File "/home/atagar/Desktop/arm/src/util/torConfig.py", line 797, in getCorrections
    skipValidation |= (torVersion is None or not torVersion.meets_requirements(stem.version.Requirement.GETINFO_CONFIG_TEXT))
AttributeError: 'Version' object has no attribute 'meets_requirements'