Fix python 3.x test regression
Oops, my recent change to skip the installation test when offline broke
python3...

  ======================================================================
  ERROR: installation (unittest.loader._FailedTest)
  ----------------------------------------------------------------------
  ImportError: Failed to import test module: installation
  Traceback (most recent call last):
    File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
      module = self._get_module_from_name(name)
    File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
      __import__(name)
    File "/home/atagar/Desktop/nyx/test/installation.py", line 6, in <module>
      import urllib2
  ImportError: No module named 'urllib2'