Stem calls lacked an isAlive() check
When arm's controller is detached its 'conn' and 'controller' attributes are
None. This means that all of our function calls need an isAlive() check before
using them...

atagar@morrigan:~/Desktop/arm$ ./arm
Traceback (most recent call last):
  File "./src/starter.py", line 566, in <module>
    _loadConfigurationDescriptions(pathPrefix)
  File "./src/starter.py", line 162, in _loadConfigurationDescriptions
    util.torConfig.loadOptionDescriptions(descriptorPath)
  File "/home/atagar/Desktop/arm/src/util/torConfig.py", line 137, in loadOptionDescriptions
    torVersion = torTools.getConn().getInfo("version", "")
  File "/home/atagar/Desktop/arm/src/util/torTools.py", line 725, in getInfo
    return self.controller.get_info(param, default)
AttributeError: 'NoneType' object has no attribute 'get_info'

Ideally we'd just drop arm's controller and use stem's (which has its own
locks and check for this), but that'll need to come later.