Unable to index into dict keys/values
The dict's keys() and values() methods provide iterators which we can't index
into...

  TypeError: 'dict_values' object does not support indexing