Suppress errors if os.putenv doesn't work
These are to sidestep issues on some platforms. Generally certainly fine if
they don't take effect. Caught thanks to tor-relays@ beta tester on FreeBSD...

  nyx: environment corrupt; missing value for
  Traceback (most recent call last):
    File "./run_nyx", line 14, in <module>
      nyx.main()
    File "/usr/home/ryan/nyx/nyx/__init__.py", line 147, in main
      nyx.starter.main()
    File "/usr/home/ryan/nyx/stem/util/conf.py", line 289, in wrapped
      return func(*args, config = config, **kwargs)
    File "/usr/home/ryan/nyx/nyx/starter.py", line 90, in main
      os.putenv('LANG', 'C')  # make subcommands (ps, netstat, etc) provide
  english results
  OSError: [Errno 14] Bad address