New tor config options crashed nyx when shown
Oops! When tor provided an option stem didn't yet have manual information for
unexpected None values caused us to stacktrace...

  https://trac.torproject.org/projects/tor/ticket/24401

  File "/usr/local/bin/nyx", line 11, in <module>
      sys.exit(main())
    ...
    File "/usr/local/lib/python3.5/dist-packages/nyx/panel/config.py", line 315, in _draw
      _draw_line(subwindow, scroll_offset, DETAILS_HEIGHT + i, entry, entry == selected, value_width, description_width)
    File "/usr/local/lib/python3.5/dist-packages/nyx/panel/config.py", line 335, in _draw_line
      attr = [CONFIG['attr.config.category_color'].get(entry.category, WHITE)]
    File "/usr/local/lib/python3.5/dist-packages/nyx/panel/config.py", line 136, in category
      return getattr(manual(self.name), 'category')
  AttributeError: 'NoneType' object has no attribute 'category'

In practice I expect this only comes up when pressing 'a' to show all config
options. That said, none the less an icky bug.