Menus caused stacktrace when you pressed 'm'
Issue spotted by Steven. Revisions to popup handling broke the menu...

  Traceback (most recent call last):
    File "./run_nyx", line 8, in <module>
      nyx.main()
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 30, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 288, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 91, in main
      curses.wrapper(nyx.controller.start_nyx)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
      return func(stdscr, *args, **kwds)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 594, in start_nyx
      nyx.menu.menu.show_menu()
    File "/home/atagar/Desktop/nyx/nyx/menu/menu.py", line 119, in show_menu
      _draw_submenu(cursor, 1, 1, selection_left)
    File "/home/atagar/Desktop/nyx/nyx/menu/menu.py", line 159, in _draw_submenu
      popup, _, _ = nyx.popups.init(len(submenu.get_children()), menu_width, top, left, below_static = False)
  AttributeError: 'module' object has no attribute 'init'