Graph panel stacktrace due to float width
Ewww I suspect we're gonna be stumbling on these for a while. This one
manifests as...

  TypeError: slice indices must be integers or None or have an __index__ method