Only provide curses.halfdelay() an int
We added a min() call to ensure we weren't out of a valid range but this caused
us to provide a float. This makes curses sad...

  Traceback (most recent call last):
    File "./run_nyx", line 8, in <module>
      nyx.main()
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 56, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 289, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 86, in main
      nyx.curses.start(nyx.controller.start_nyx, transparent_background = True, cursor = False)
    File "/home/atagar/Desktop/nyx/nyx/curses.py", line 169, in start
      curses.wrapper(_wrapper)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
      return func(stdscr, *args, **kwds)
    File "/home/atagar/Desktop/nyx/nyx/curses.py", line 167, in _wrapper
      function()
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 370, in start_nyx
      confirmation_key = show_message(msg, BOLD, max_wait = 30)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 63, in show_message
      return header_panel.show_message(message, *attr, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/panel/header.py", line 75, in show_message
      user_input = nyx.curses.key_input(kwargs['max_wait'])
    File "/home/atagar/Desktop/nyx/nyx/curses.py", line 214, in key_input
      curses.halfdelay(min(input_timeout, 25.5) * 10)
  TypeError: integer argument expected, got float