Replace deprecated LogBuffer
Stem 2.x drops deprecated classes. As a result we error with...

  Traceback (most recent call last):
    File "./run_nyx", line 7, in <module>
      import nyx
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 779, in <module>
      import nyx.panel.log
    File "/home/atagar/Desktop/nyx/nyx/panel/log.py", line 69, in <module>
      NYX_LOGGER = log.LogBuffer(log.Runlevel.DEBUG, yield_records = True)
  AttributeError: module 'stem.util.log' has no attribute 'LogBuffer'

This was removed in stem commit 76b6b49. Fortunately it's a simple class to
replace.