Missing stem import
We were missing an import for stem. This was fine until we hit an exception
condition...

Traceback (most recent call last):
  File "./src/starter.py", line 590, in <module>
    cli.controller.startTorMonitor(time.time() - initTime)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 705, in startTorMonitor
    curses.wrapper(drawTorMonitor, startTime)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 761, in drawTorMonitor
    control.redraw(False)
  File "/home/atagar/Desktop/arm/src/cli/controller.py", line 351, in redraw
    panelImpl.redraw(force)
  File "/home/atagar/Desktop/arm/src/util/panel.py", line 408, in redraw
    self.draw(self.maxX, self.maxY)
  File "/home/atagar/Desktop/arm/src/cli/connections/connPanel.py", line 388, in draw
    drawEntry = entryLine.getListingEntry(width - scrollOffset - len(prefix), currentTime, self._listingType)
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 290, in getListingEntry
    myListing = entries.ConnectionPanelLine.getListingEntry(self, width, currentTime, listingType)
  File "/home/atagar/Desktop/arm/src/cli/connections/entries.py", line 136, in getListingEntry
    self._listingCache = self._getListingEntry(width, currentTime, listingType)
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 324, in _getListingEntry
    (self._getListingContent(width - (12 + timeWidth) - 1, listingType), lineFormat),
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 608, in _getListingContent
    etc = self.getEtcContent(width - usedSpace, listingType)
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 482, in getEtcContent
    nicknameLabel = uiTools.cropStr(self.foreign.getNickname(), nicknameSpace, 0)
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 139, in getNickname
    myFingerprint = self.getFingerprint()
  File "/home/atagar/Desktop/arm/src/cli/connections/connEntry.py", line 123, in getFingerprint
    myFingerprint = conn.getRelayFingerprint(self.ipAddr)
  File "/home/atagar/Desktop/arm/src/util/torTools.py", line 1228, in getRelayFingerprint
    relayFingerprint = self._getRelayFingerprint(relayAddress, relayPort)
  File "/home/atagar/Desktop/arm/src/util/torTools.py", line 1874, in _getRelayFingerprint
    if relayAddress == self.getInfo("address", None):
  File "/home/atagar/Desktop/arm/src/util/torTools.py", line 727, in getInfo
    except stem.SocketClosed, exc:
NameError: global name 'stem' is not defined