Fix menu's 'exit' option
Earlier change that dropped the quit method broke our menu, causing nyx to
crash with the following when you bring it up...

  Traceback (most recent call last):
    File "./run_nyx", line 60, in <module>
      main()
    File "./run_nyx", line 17, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 288, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 91, in main
      curses.wrapper(nyx.controller.start_nyx)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
      return func(stdscr, *args, **kwds)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 590, in start_nyx
      nyx.menu.menu.show_menu()
    File "/home/atagar/Desktop/nyx/nyx/menu/menu.py", line 90, in show_menu
      menu = nyx.menu.actions.make_menu()
    File "/home/atagar/Desktop/nyx/nyx/menu/actions.py", line 31, in make_menu
      base_menu.add(make_actions_menu())
    File "/home/atagar/Desktop/nyx/nyx/menu/actions.py", line 81, in make_actions_menu
      actions_menu.add(nyx.menu.item.MenuItem('Exit', control.quit))
  AttributeError: Controller instance has no attribute 'quit'