Popup for writing torrc caused stacktrace
The popup wasn't updated to use the new method of nyx.popup...

  Traceback (most recent call last):
    File "./run_nyx", line 8, in <module>
      nyx.main()
    File "/home/atagar/Desktop/nyx/nyx/__init__.py", line 31, in main
      nyx.starter.main()
    File "/home/atagar/Desktop/nyx/stem/util/conf.py", line 289, in wrapped
      return func(*args, config = config, **kwargs)
    File "/home/atagar/Desktop/nyx/nyx/starter.py", line 89, in main
      curses.wrapper(nyx.controller.start_nyx)
    File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
      return func(stdscr, *args, **kwds)
    File "/home/atagar/Desktop/nyx/nyx/controller.py", line 624, in start_nyx
      is_keystroke_consumed = panel_impl.handle_key(key)
    File "/home/atagar/Desktop/nyx/nyx/config_panel.py", line 303, in handle_key
      self.show_write_dialog()
    File "/home/atagar/Desktop/nyx/nyx/config_panel.py", line 318, in show_write_dialog
      popup, width, height = nyx.popups.init(len(config_lines) + 2)
  AttributeError: 'module' object has no attribute 'init'