Error due to moved popup import
Oops, fixing an error from rearanging our imports. This came up when pressing
'e' to get the logging popup...

Traceback (most recent call last):
  File "runner.py", line 3, in <module>
    arm.starter.main()
  File "/home/atagar/Desktop/arm/arm/starter.py", line 398, in main
    arm.controller.start_arm(start_time)
  File "/home/atagar/Desktop/arm/arm/controller.py", line 549, in start_arm
    curses.wrapper(drawTorMonitor, start_time)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/atagar/Desktop/arm/arm/controller.py", line 654, in drawTorMonitor
    isKeystrokeConsumed = panelImpl.handleKey(key)
  File "/home/atagar/Desktop/arm/arm/logPanel.py", line 879, in handleKey
    self.showEventSelectionPrompt()
  File "/home/atagar/Desktop/arm/arm/logPanel.py", line 756, in showEventSelectionPrompt
    popup, width, height = popups.init(11, 80)
NameError: global name 'popups' is not defined